# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(867, 693)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(51, 22, 461, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_Pioche = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_Pioche.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_Pioche.setObjectName("gridLayout_Pioche")
        self.pushButton_17 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_17.setText("")
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_Pioche.addWidget(self.pushButton_17, 0, 0, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_28.setText("")
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout_Pioche.addWidget(self.pushButton_28, 0, 1, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_16.setText("")
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_Pioche.addWidget(self.pushButton_16, 0, 2, 1, 1)
        self.pushButton_27 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_27.setText("")
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout_Pioche.addWidget(self.pushButton_27, 0, 3, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_26.setText("")
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout_Pioche.addWidget(self.pushButton_26, 0, 4, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_22.setText("")
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_Pioche.addWidget(self.pushButton_22, 0, 5, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_20.setText("")
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_Pioche.addWidget(self.pushButton_20, 0, 6, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_15.setText("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_Pioche.addWidget(self.pushButton_15, 1, 0, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_21.setText("")
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_Pioche.addWidget(self.pushButton_21, 1, 1, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_19.setText("")
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_Pioche.addWidget(self.pushButton_19, 1, 2, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_24.setText("")
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_Pioche.addWidget(self.pushButton_24, 1, 3, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_23.setText("")
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_Pioche.addWidget(self.pushButton_23, 1, 4, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_25.setText("")
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout_Pioche.addWidget(self.pushButton_25, 1, 5, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_18.setText("")
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_Pioche.addWidget(self.pushButton_18, 1, 6, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(50, 535, 461, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_J2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_J2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_J2.setObjectName("gridLayout_J2")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_J2.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_J2.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_J2.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_J2.addWidget(self.pushButton_4, 0, 3, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_14.setText("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_J2.addWidget(self.pushButton_14, 0, 4, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_J2.addWidget(self.pushButton_9, 0, 5, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_13.setText("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_J2.addWidget(self.pushButton_13, 0, 6, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(50, 590, 461, 51))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_J1 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_J1.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_J1.setObjectName("gridLayout_J1")
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_J1.addWidget(self.pushButton_6, 0, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_J1.addWidget(self.pushButton_8, 0, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_J1.addWidget(self.pushButton_5, 0, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_J1.addWidget(self.pushButton_7, 0, 3, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_J1.addWidget(self.pushButton_11, 0, 4, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_J1.addWidget(self.pushButton_10, 0, 5, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_J1.addWidget(self.pushButton_12, 0, 6, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(32, 170, 536, 306))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_Plateau = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_Plateau.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_Plateau.setObjectName("gridLayout_Plateau")
        self.pushButton_29 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_29.setText("")
        self.pushButton_29.setObjectName("pushButton_29")
        self.gridLayout_Plateau.addWidget(self.pushButton_29, 0, 0, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_30.setText("")
        self.pushButton_30.setObjectName("pushButton_30")
        self.gridLayout_Plateau.addWidget(self.pushButton_30, 0, 1, 1, 1)
        self.pushButton_31 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_31.setText("")
        self.pushButton_31.setObjectName("pushButton_31")
        self.gridLayout_Plateau.addWidget(self.pushButton_31, 0, 2, 1, 1)
        self.pushButton_32 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_32.setText("")
        self.pushButton_32.setObjectName("pushButton_32")
        self.gridLayout_Plateau.addWidget(self.pushButton_32, 0, 3, 1, 1)
        self.pushButton_33 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_33.setText("")
        self.pushButton_33.setObjectName("pushButton_33")
        self.gridLayout_Plateau.addWidget(self.pushButton_33, 0, 4, 1, 1)
        self.pushButton_49 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_49.setText("")
        self.pushButton_49.setObjectName("pushButton_49")
        self.gridLayout_Plateau.addWidget(self.pushButton_49, 0, 5, 1, 1)
        self.pushButton_55 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_55.setText("")
        self.pushButton_55.setObjectName("pushButton_55")
        self.gridLayout_Plateau.addWidget(self.pushButton_55, 0, 6, 1, 1)
        self.pushButton_93 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_93.setText("")
        self.pushButton_93.setObjectName("pushButton_93")
        self.gridLayout_Plateau.addWidget(self.pushButton_93, 0, 7, 1, 1)
        self.pushButton_88 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_88.setText("")
        self.pushButton_88.setObjectName("pushButton_88")
        self.gridLayout_Plateau.addWidget(self.pushButton_88, 0, 8, 1, 1)
        self.pushButton_94 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_94.setText("")
        self.pushButton_94.setObjectName("pushButton_94")
        self.gridLayout_Plateau.addWidget(self.pushButton_94, 0, 9, 1, 1)
        self.pushButton_36 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_36.setText("")
        self.pushButton_36.setObjectName("pushButton_36")
        self.gridLayout_Plateau.addWidget(self.pushButton_36, 1, 0, 1, 1)
        self.pushButton_35 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_35.setText("")
        self.pushButton_35.setObjectName("pushButton_35")
        self.gridLayout_Plateau.addWidget(self.pushButton_35, 1, 1, 1, 1)
        self.pushButton_37 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_37.setText("")
        self.pushButton_37.setObjectName("pushButton_37")
        self.gridLayout_Plateau.addWidget(self.pushButton_37, 1, 2, 1, 1)
        self.pushButton_34 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_34.setText("")
        self.pushButton_34.setObjectName("pushButton_34")
        self.gridLayout_Plateau.addWidget(self.pushButton_34, 1, 3, 1, 1)
        self.pushButton_38 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_38.setText("")
        self.pushButton_38.setObjectName("pushButton_38")
        self.gridLayout_Plateau.addWidget(self.pushButton_38, 1, 4, 1, 1)
        self.pushButton_52 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_52.setText("")
        self.pushButton_52.setObjectName("pushButton_52")
        self.gridLayout_Plateau.addWidget(self.pushButton_52, 1, 5, 1, 1)
        self.pushButton_56 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_56.setText("")
        self.pushButton_56.setObjectName("pushButton_56")
        self.gridLayout_Plateau.addWidget(self.pushButton_56, 1, 6, 1, 1)
        self.pushButton_98 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_98.setText("")
        self.pushButton_98.setObjectName("pushButton_98")
        self.gridLayout_Plateau.addWidget(self.pushButton_98, 1, 7, 1, 1)
        self.pushButton_95 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_95.setText("")
        self.pushButton_95.setObjectName("pushButton_95")
        self.gridLayout_Plateau.addWidget(self.pushButton_95, 1, 8, 1, 1)
        self.pushButton_92 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_92.setText("")
        self.pushButton_92.setObjectName("pushButton_92")
        self.gridLayout_Plateau.addWidget(self.pushButton_92, 1, 9, 1, 1)
        self.pushButton_44 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_44.setText("")
        self.pushButton_44.setObjectName("pushButton_44")
        self.gridLayout_Plateau.addWidget(self.pushButton_44, 2, 0, 1, 1)
        self.pushButton_43 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_43.setText("")
        self.pushButton_43.setObjectName("pushButton_43")
        self.gridLayout_Plateau.addWidget(self.pushButton_43, 2, 1, 1, 1)
        self.pushButton_46 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_46.setText("")
        self.pushButton_46.setObjectName("pushButton_46")
        self.gridLayout_Plateau.addWidget(self.pushButton_46, 2, 2, 1, 1)
        self.pushButton_39 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_39.setText("")
        self.pushButton_39.setObjectName("pushButton_39")
        self.gridLayout_Plateau.addWidget(self.pushButton_39, 2, 3, 1, 1)
        self.pushButton_47 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_47.setText("")
        self.pushButton_47.setObjectName("pushButton_47")
        self.gridLayout_Plateau.addWidget(self.pushButton_47, 2, 4, 1, 1)
        self.pushButton_51 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_51.setText("")
        self.pushButton_51.setObjectName("pushButton_51")
        self.gridLayout_Plateau.addWidget(self.pushButton_51, 2, 5, 1, 1)
        self.pushButton_54 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_54.setText("")
        self.pushButton_54.setObjectName("pushButton_54")
        self.gridLayout_Plateau.addWidget(self.pushButton_54, 2, 6, 1, 1)
        self.pushButton_90 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_90.setText("")
        self.pushButton_90.setObjectName("pushButton_90")
        self.gridLayout_Plateau.addWidget(self.pushButton_90, 2, 7, 1, 1)
        self.pushButton_96 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_96.setText("")
        self.pushButton_96.setObjectName("pushButton_96")
        self.gridLayout_Plateau.addWidget(self.pushButton_96, 2, 8, 1, 1)
        self.pushButton_81 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_81.setText("")
        self.pushButton_81.setObjectName("pushButton_81")
        self.gridLayout_Plateau.addWidget(self.pushButton_81, 2, 9, 1, 1)
        self.pushButton_48 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_48.setText("")
        self.pushButton_48.setObjectName("pushButton_48")
        self.gridLayout_Plateau.addWidget(self.pushButton_48, 3, 0, 1, 1)
        self.pushButton_42 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_42.setText("")
        self.pushButton_42.setObjectName("pushButton_42")
        self.gridLayout_Plateau.addWidget(self.pushButton_42, 3, 1, 1, 1)
        self.pushButton_40 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_40.setText("")
        self.pushButton_40.setObjectName("pushButton_40")
        self.gridLayout_Plateau.addWidget(self.pushButton_40, 3, 2, 1, 1)
        self.pushButton_45 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_45.setText("")
        self.pushButton_45.setObjectName("pushButton_45")
        self.gridLayout_Plateau.addWidget(self.pushButton_45, 3, 3, 1, 1)
        self.pushButton_41 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_41.setText("")
        self.pushButton_41.setObjectName("pushButton_41")
        self.gridLayout_Plateau.addWidget(self.pushButton_41, 3, 4, 1, 1)
        self.pushButton_50 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_50.setText("")
        self.pushButton_50.setObjectName("pushButton_50")
        self.gridLayout_Plateau.addWidget(self.pushButton_50, 3, 5, 1, 1)
        self.pushButton_53 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_53.setText("")
        self.pushButton_53.setObjectName("pushButton_53")
        self.gridLayout_Plateau.addWidget(self.pushButton_53, 3, 6, 1, 1)
        self.pushButton_97 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_97.setText("")
        self.pushButton_97.setObjectName("pushButton_97")
        self.gridLayout_Plateau.addWidget(self.pushButton_97, 3, 7, 1, 1)
        self.pushButton_85 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_85.setText("")
        self.pushButton_85.setObjectName("pushButton_85")
        self.gridLayout_Plateau.addWidget(self.pushButton_85, 3, 8, 1, 1)
        self.pushButton_79 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_79.setText("")
        self.pushButton_79.setObjectName("pushButton_79")
        self.gridLayout_Plateau.addWidget(self.pushButton_79, 3, 9, 1, 1)
        self.pushButton_65 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_65.setText("")
        self.pushButton_65.setObjectName("pushButton_65")
        self.gridLayout_Plateau.addWidget(self.pushButton_65, 4, 0, 1, 1)
        self.pushButton_72 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_72.setText("")
        self.pushButton_72.setObjectName("pushButton_72")
        self.gridLayout_Plateau.addWidget(self.pushButton_72, 4, 1, 1, 1)
        self.pushButton_59 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_59.setText("")
        self.pushButton_59.setObjectName("pushButton_59")
        self.gridLayout_Plateau.addWidget(self.pushButton_59, 4, 2, 1, 1)
        self.pushButton_62 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_62.setText("")
        self.pushButton_62.setObjectName("pushButton_62")
        self.gridLayout_Plateau.addWidget(self.pushButton_62, 4, 3, 1, 1)
        self.pushButton_77 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_77.setText("")
        self.pushButton_77.setObjectName("pushButton_77")
        self.gridLayout_Plateau.addWidget(self.pushButton_77, 4, 4, 1, 1)
        self.pushButton_74 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_74.setText("")
        self.pushButton_74.setObjectName("pushButton_74")
        self.gridLayout_Plateau.addWidget(self.pushButton_74, 4, 5, 1, 1)
        self.pushButton_73 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_73.setText("")
        self.pushButton_73.setObjectName("pushButton_73")
        self.gridLayout_Plateau.addWidget(self.pushButton_73, 4, 6, 1, 1)
        self.pushButton_83 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_83.setText("")
        self.pushButton_83.setObjectName("pushButton_83")
        self.gridLayout_Plateau.addWidget(self.pushButton_83, 4, 7, 1, 1)
        self.pushButton_78 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_78.setText("")
        self.pushButton_78.setObjectName("pushButton_78")
        self.gridLayout_Plateau.addWidget(self.pushButton_78, 4, 8, 1, 1)
        self.pushButton_84 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_84.setText("")
        self.pushButton_84.setObjectName("pushButton_84")
        self.gridLayout_Plateau.addWidget(self.pushButton_84, 4, 9, 1, 1)
        self.pushButton_71 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_71.setText("")
        self.pushButton_71.setObjectName("pushButton_71")
        self.gridLayout_Plateau.addWidget(self.pushButton_71, 5, 0, 1, 1)
        self.pushButton_69 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_69.setText("")
        self.pushButton_69.setObjectName("pushButton_69")
        self.gridLayout_Plateau.addWidget(self.pushButton_69, 5, 1, 1, 1)
        self.pushButton_67 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_67.setText("")
        self.pushButton_67.setObjectName("pushButton_67")
        self.gridLayout_Plateau.addWidget(self.pushButton_67, 5, 2, 1, 1)
        self.pushButton_60 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_60.setText("")
        self.pushButton_60.setObjectName("pushButton_60")
        self.gridLayout_Plateau.addWidget(self.pushButton_60, 5, 3, 1, 1)
        self.pushButton_70 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_70.setText("")
        self.pushButton_70.setObjectName("pushButton_70")
        self.gridLayout_Plateau.addWidget(self.pushButton_70, 5, 4, 1, 1)
        self.pushButton_75 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_75.setText("")
        self.pushButton_75.setObjectName("pushButton_75")
        self.gridLayout_Plateau.addWidget(self.pushButton_75, 5, 5, 1, 1)
        self.pushButton_58 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_58.setText("")
        self.pushButton_58.setObjectName("pushButton_58")
        self.gridLayout_Plateau.addWidget(self.pushButton_58, 5, 6, 1, 1)
        self.pushButton_89 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_89.setText("")
        self.pushButton_89.setObjectName("pushButton_89")
        self.gridLayout_Plateau.addWidget(self.pushButton_89, 5, 7, 1, 1)
        self.pushButton_80 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_80.setText("")
        self.pushButton_80.setObjectName("pushButton_80")
        self.gridLayout_Plateau.addWidget(self.pushButton_80, 5, 8, 1, 1)
        self.pushButton_87 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_87.setText("")
        self.pushButton_87.setObjectName("pushButton_87")
        self.gridLayout_Plateau.addWidget(self.pushButton_87, 5, 9, 1, 1)
        self.pushButton_63 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_63.setText("")
        self.pushButton_63.setObjectName("pushButton_63")
        self.gridLayout_Plateau.addWidget(self.pushButton_63, 6, 0, 1, 1)
        self.pushButton_64 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_64.setText("")
        self.pushButton_64.setObjectName("pushButton_64")
        self.gridLayout_Plateau.addWidget(self.pushButton_64, 6, 1, 1, 1)
        self.pushButton_68 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_68.setText("")
        self.pushButton_68.setObjectName("pushButton_68")
        self.gridLayout_Plateau.addWidget(self.pushButton_68, 6, 2, 1, 1)
        self.pushButton_61 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_61.setText("")
        self.pushButton_61.setObjectName("pushButton_61")
        self.gridLayout_Plateau.addWidget(self.pushButton_61, 6, 3, 1, 1)
        self.pushButton_76 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_76.setText("")
        self.pushButton_76.setObjectName("pushButton_76")
        self.gridLayout_Plateau.addWidget(self.pushButton_76, 6, 4, 1, 1)
        self.pushButton_66 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_66.setText("")
        self.pushButton_66.setObjectName("pushButton_66")
        self.gridLayout_Plateau.addWidget(self.pushButton_66, 6, 5, 1, 1)
        self.pushButton_57 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_57.setText("")
        self.pushButton_57.setObjectName("pushButton_57")
        self.gridLayout_Plateau.addWidget(self.pushButton_57, 6, 6, 1, 1)
        self.pushButton_82 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_82.setText("")
        self.pushButton_82.setObjectName("pushButton_82")
        self.gridLayout_Plateau.addWidget(self.pushButton_82, 6, 7, 1, 1)
        self.pushButton_86 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_86.setText("")
        self.pushButton_86.setObjectName("pushButton_86")
        self.gridLayout_Plateau.addWidget(self.pushButton_86, 6, 8, 1, 1)
        self.pushButton_91 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_91.setText("")
        self.pushButton_91.setObjectName("pushButton_91")
        self.gridLayout_Plateau.addWidget(self.pushButton_91, 6, 9, 1, 1)
        self.pushButton_113 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_113.setText("")
        self.pushButton_113.setObjectName("pushButton_113")
        self.gridLayout_Plateau.addWidget(self.pushButton_113, 7, 0, 1, 1)
        self.pushButton_115 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_115.setText("")
        self.pushButton_115.setObjectName("pushButton_115")
        self.gridLayout_Plateau.addWidget(self.pushButton_115, 7, 1, 1, 1)
        self.pushButton_122 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_122.setText("")
        self.pushButton_122.setObjectName("pushButton_122")
        self.gridLayout_Plateau.addWidget(self.pushButton_122, 7, 2, 1, 1)
        self.pushButton_104 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_104.setText("")
        self.pushButton_104.setObjectName("pushButton_104")
        self.gridLayout_Plateau.addWidget(self.pushButton_104, 7, 3, 1, 1)
        self.pushButton_110 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_110.setText("")
        self.pushButton_110.setObjectName("pushButton_110")
        self.gridLayout_Plateau.addWidget(self.pushButton_110, 7, 4, 1, 1)
        self.pushButton_100 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_100.setText("")
        self.pushButton_100.setObjectName("pushButton_100")
        self.gridLayout_Plateau.addWidget(self.pushButton_100, 7, 5, 1, 1)
        self.pushButton_112 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_112.setText("")
        self.pushButton_112.setObjectName("pushButton_112")
        self.gridLayout_Plateau.addWidget(self.pushButton_112, 7, 6, 1, 1)
        self.pushButton_124 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_124.setText("")
        self.pushButton_124.setObjectName("pushButton_124")
        self.gridLayout_Plateau.addWidget(self.pushButton_124, 7, 7, 1, 1)
        self.pushButton_114 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_114.setText("")
        self.pushButton_114.setObjectName("pushButton_114")
        self.gridLayout_Plateau.addWidget(self.pushButton_114, 7, 8, 1, 1)
        self.pushButton_123 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_123.setText("")
        self.pushButton_123.setObjectName("pushButton_123")
        self.gridLayout_Plateau.addWidget(self.pushButton_123, 7, 9, 1, 1)
        self.pushButton_125 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_125.setText("")
        self.pushButton_125.setObjectName("pushButton_125")
        self.gridLayout_Plateau.addWidget(self.pushButton_125, 8, 0, 1, 1)
        self.pushButton_118 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_118.setText("")
        self.pushButton_118.setObjectName("pushButton_118")
        self.gridLayout_Plateau.addWidget(self.pushButton_118, 8, 1, 1, 1)
        self.pushButton_111 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_111.setText("")
        self.pushButton_111.setObjectName("pushButton_111")
        self.gridLayout_Plateau.addWidget(self.pushButton_111, 8, 2, 1, 1)
        self.pushButton_126 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_126.setText("")
        self.pushButton_126.setObjectName("pushButton_126")
        self.gridLayout_Plateau.addWidget(self.pushButton_126, 8, 3, 1, 1)
        self.pushButton_119 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_119.setText("")
        self.pushButton_119.setObjectName("pushButton_119")
        self.gridLayout_Plateau.addWidget(self.pushButton_119, 8, 4, 1, 1)
        self.pushButton_101 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_101.setText("")
        self.pushButton_101.setObjectName("pushButton_101")
        self.gridLayout_Plateau.addWidget(self.pushButton_101, 8, 5, 1, 1)
        self.pushButton_117 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_117.setText("")
        self.pushButton_117.setObjectName("pushButton_117")
        self.gridLayout_Plateau.addWidget(self.pushButton_117, 8, 6, 1, 1)
        self.pushButton_99 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_99.setText("")
        self.pushButton_99.setObjectName("pushButton_99")
        self.gridLayout_Plateau.addWidget(self.pushButton_99, 8, 7, 1, 1)
        self.pushButton_105 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_105.setText("")
        self.pushButton_105.setObjectName("pushButton_105")
        self.gridLayout_Plateau.addWidget(self.pushButton_105, 8, 8, 1, 1)
        self.pushButton_103 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_103.setText("")
        self.pushButton_103.setObjectName("pushButton_103")
        self.gridLayout_Plateau.addWidget(self.pushButton_103, 8, 9, 1, 1)
        self.pushButton_106 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_106.setText("")
        self.pushButton_106.setObjectName("pushButton_106")
        self.gridLayout_Plateau.addWidget(self.pushButton_106, 9, 0, 1, 1)
        self.pushButton_102 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_102.setText("")
        self.pushButton_102.setObjectName("pushButton_102")
        self.gridLayout_Plateau.addWidget(self.pushButton_102, 9, 1, 1, 1)
        self.pushButton_121 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_121.setText("")
        self.pushButton_121.setObjectName("pushButton_121")
        self.gridLayout_Plateau.addWidget(self.pushButton_121, 9, 2, 1, 1)
        self.pushButton_109 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_109.setText("")
        self.pushButton_109.setObjectName("pushButton_109")
        self.gridLayout_Plateau.addWidget(self.pushButton_109, 9, 3, 1, 1)
        self.pushButton_107 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_107.setText("")
        self.pushButton_107.setObjectName("pushButton_107")
        self.gridLayout_Plateau.addWidget(self.pushButton_107, 9, 4, 1, 1)
        self.pushButton_116 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_116.setText("")
        self.pushButton_116.setObjectName("pushButton_116")
        self.gridLayout_Plateau.addWidget(self.pushButton_116, 9, 5, 1, 1)
        self.pushButton_120 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_120.setText("")
        self.pushButton_120.setObjectName("pushButton_120")
        self.gridLayout_Plateau.addWidget(self.pushButton_120, 9, 6, 1, 1)
        self.pushButton_127 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_127.setText("")
        self.pushButton_127.setObjectName("pushButton_127")
        self.gridLayout_Plateau.addWidget(self.pushButton_127, 9, 7, 1, 1)
        self.pushButton_108 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_108.setText("")
        self.pushButton_108.setObjectName("pushButton_108")
        self.gridLayout_Plateau.addWidget(self.pushButton_108, 9, 8, 1, 1)
        self.pushButton_128 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_128.setText("")
        self.pushButton_128.setObjectName("pushButton_128")
        self.gridLayout_Plateau.addWidget(self.pushButton_128, 9, 9, 1, 1)
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(550, 550, 281, 120))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_Commande = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_Commande.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_Commande.setObjectName("gridLayout_Commande")
        self.pushButton_130 = QtWidgets.QPushButton(self.layoutWidget4)
        self.pushButton_130.setObjectName("pushButton_130")
        self.gridLayout_Commande.addWidget(self.pushButton_130, 2, 1, 1, 1)
        self.pushButton_136 = QtWidgets.QPushButton(self.layoutWidget4)
        self.pushButton_136.setObjectName("pushButton_136")
        self.gridLayout_Commande.addWidget(self.pushButton_136, 2, 0, 1, 1)
        self.pushButton_129 = QtWidgets.QPushButton(self.layoutWidget4)
        self.pushButton_129.setObjectName("pushButton_129")
        self.gridLayout_Commande.addWidget(self.pushButton_129, 0, 0, 1, 1)
        self.pushButton_131 = QtWidgets.QPushButton(self.layoutWidget4)
        self.pushButton_131.setObjectName("pushButton_131")
        self.gridLayout_Commande.addWidget(self.pushButton_131, 3, 0, 1, 1)
        self.pushButton_134 = QtWidgets.QPushButton(self.layoutWidget4)
        self.pushButton_134.setObjectName("pushButton_134")
        self.gridLayout_Commande.addWidget(self.pushButton_134, 0, 2, 1, 1)
        self.pushButton_135 = QtWidgets.QPushButton(self.layoutWidget4)
        self.pushButton_135.setObjectName("pushButton_135")
        self.gridLayout_Commande.addWidget(self.pushButton_135, 3, 2, 1, 1)
        self.pushButton_132 = QtWidgets.QPushButton(self.layoutWidget4)
        self.pushButton_132.setObjectName("pushButton_132")
        self.gridLayout_Commande.addWidget(self.pushButton_132, 0, 1, 1, 1)
        self.pushButton_133 = QtWidgets.QPushButton(self.layoutWidget4)
        self.pushButton_133.setText("")
        self.pushButton_133.setObjectName("pushButton_133")
        self.gridLayout_Commande.addWidget(self.pushButton_133, 3, 1, 1, 1)
        self.pushButton_137 = QtWidgets.QPushButton(self.layoutWidget4)
        self.pushButton_137.setObjectName("pushButton_137")
        self.gridLayout_Commande.addWidget(self.pushButton_137, 2, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 867, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_130.setText(_translate("MainWindow", "n"))
        self.pushButton_136.setText(_translate("MainWindow", "g"))
        self.pushButton_129.setText(_translate("MainWindow", "hg"))
        self.pushButton_131.setText(_translate("MainWindow", "bg"))
        self.pushButton_134.setText(_translate("MainWindow", "hd"))
        self.pushButton_135.setText(_translate("MainWindow", "bd"))
        self.pushButton_132.setText(_translate("MainWindow", "r"))
        self.pushButton_137.setText(_translate("MainWindow", "d"))

